FROM nginx:alpine

# Устанавливаем рабочую директорию
WORKDIR /usr/share/nginx/html

# Копируем статические файлы в Nginx
COPY . .

# Указываем порт для Nginx
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
