FROM nginx:alpine

# Копируем статические файлы в директорию, обслуживаемую Nginx
WORKDIR /usr/share/nginx/html
COPY ./frontend /usr/share/nginx/html

# Указываем порт, который Nginx будет слушать
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]