services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: fastapi_app
    env_file:
      - .env
    #expose:
    #  - 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    #volumes:
    #  - static_volume:/frontend/static
    command: >
          sh -c "
                 alembic upgrade head &&
                 poetry run uvicorn main:app --host 0.0.0.0 --port 8000"
    #healthcheck:
    #  test: [ "CMD", "curl", "-f", "http://localhost:8000/currencies" ]
    #  interval: 10s
    #  timeout: 5s
    #  retries: 5

  #frontend:
  #  build:
  #    context: ./frontend/
  #    dockerfile: Dockerfile.frontend
  #  container_name: react_app
  #  volumes:
  #    - static_volume:
  #  #restart: always
  #  depends_on:
  #    - backend
# #       condition: service_healthy
  #  ports:
  #    - "80:80"

volumes:
  postgres_data:
