# version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  app:
    build:
      context: . # Использует Dockerfile в корневой директории
      dockerfile: Dockerfile.dev
    container_name: fastapi_app
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app  # Чтобы использовать локальный код
    ports:
      - "8000:8000"
    command: >
      sh -c "
      alembic upgrade head &&
      poetry run uvicorn main:app --host 0.0.0.0 --port 8000
      "

volumes:
  postgres_data: